# Generated by Django 2.2.13 on 2020-08-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(max_length=5)),
                ('comment', models.CharField(max_length=500)),
                ('sentiment', models.FloatField()),
            ],
        ),
    ]
