# Generated by Django 2.2.13 on 2020-08-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0002_auto_20200809_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='short',
        ),
    ]
